name: Portfolio Finders

on:
  issues:
    types: [opened]
permissions:
  contents: write
jobs:
  add-solver:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Extract Flag and update README
        run: |
          issue_body="${{ github.event.issue.body }}"
          name_line=$(echo "$issue_body" | grep -i "Enter the flag" -A 2 | tail -n1)
          name=$(echo "$name_line" | xargs)

          echo "Adding solver: $name"

          sed -i "/<!-- SOLVER_LIST_START -->/a * $name" README.md

          git config --global user.name "sanjaykannan8"
          git config --global user.email "noobg900@gmail.com"
          git add README.md
          git commit -m "🎉 Added $name to solver list"
          git push
          
