name: Portfolio Finders

on:
  issues:
    types: [opened]
permissions:
  contents: write
jobs:
  add-solver:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Extract Flag and update README
        run: |
          issue_body="${{ github.event.issue.body }}"
          name_line=$(echo "$issue_body" | grep -A 3 "Enter your flag" | tail -n1)
          name=$(echo "$name_line" | xargs)
          echo "$name"
          expected_hash="e5299296cf62003e59ae7473e626052a6d03991afa8bdeda076f562627c61d84" 
          x=0
          flag_hash=$(echo -n "$name" | sha256sum | awk '{print $1}')
          echo "$flag_hash"
          if [ "$flag_hash" != "$expected_hash" ]; then
            echo "Incorrect flag."
            exit 1
          else
            echo "Correct flag."
          fi

          echo "Adding solver: $name"

          

          git config --global user.name "sanjaykannan8"
          git config --global user.email "noobg900@gmail.com"
          git add README.md
          git commit -m "🎉 Added $name to solver list"
          git push
          
